#index:
#    path: /
#    controller: App\Controller\DefaultController::index

meals_get:
    path: /api/meals
    controller: App\Controller\MealController::index
    methods: GET

app_locales:
  resource: '../src/DataFixtures/'
  type: annotation
  prefix:
    en: '/en'
    hr: '/hr'

